Add test reporter

diff --git a/.github/workflows/dotnet-pipeline.yml b/.github/workflows/dotnet-pipeline.yml
--- a/.github/workflows/dotnet-pipeline.yml
+++ b/.github/workflows/dotnet-pipeline.yml
@@ -30,4 +30,12 @@ jobs:
       run: dotnet build ./iths.cidemo.api/*.sln --no-restore
       
     - name: Test
-      run: dotnet test ./iths.cidemo.api/*.Tests*  --no-build --verbosity normal
+      run: dotnet test ./iths.cidemo.api/*.Tests*  --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+      
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
+      with:
+        name: Test
+        path: ./iths.cidemo.api/Iths.CiDemo.Api.Tests/test-results.trx
+        reporter: dotnet-trx 
